title: dsra
description: Dynamic Site Response Analysis
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

github:
  repository_url: https://github.com/averriK/dsra

include:
  - README.md
  - index.md

exclude:
  - "**/sessions"
  - "*.sh"
  - bin/
  - examples/
  - tests/
  - src/

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
